default_stages: [push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-vcs-permalinks
      - id: end-of-file-fixer
        exclude: "tests/[test_*|data]/*"
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: debug-statements
      - id: no-commit-to-branch

  - repo: local
    hooks:
      - id: format
        name: format
        language: system
        pass_filenames: false
        entry: ./scripts/format
        types: [python]

      - id: linter and test
        name: linter and test
        language: system
        pass_filenames: false
        entry: ./scripts/test
        types: [python]
        
      - id: commitizen
        name: commitizen check
        description: "Check whether the commit message follows commiting rules"
        entry: cz check --commit-msg-file
        language: python
        language_version: python3
        require_serial: true
        minimum_pre_commit_version: "0.15.4"
